name: "Hawser"
version: "0.2.37-0"
slug: hawser
description: "Docker stack deployment and management via a remote API"
url: "https://github.com/finsys/hawser"
startup: services
arch:
  - aarch64
  - amd64
  - armv7
init: false
host_network: false
docker_api: true
ports:
  2376/tcp: 2376
ports_description:
  2376/tcp: "Hawser Docker management API"
map:
  - type: share
    read_only: false
options:
  token: "your-secret-token"
schema:
  token: str